steps:
  - name: 'gcr.io/kaniko-project/executor:v0.16.0'
    args:
      - --destination=gcr.io/c-forum/img-mkr-nuxt
      - --cache=true
      - --cache-ttl=6h
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'img-mkr-nuxt', '--image', 'gcr.io/c-forum/img-mkr-nuxt', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated']
